export interface TeamMember {
  // Employee table
  id: string;
  position: string;
  department_id: string;
  department_name: string;
  company: string;
  created_at: string; // when they joined the system

  // Users table (via user_id)
  user_id: string;
  first_name: string;
  last_name: string;
  full_name: string;
  email: string;
  phone: string;
  last_login: string | null;

  // Derived / computed
  total_visits_received: number;   // how many visitors came to meet this employee
  visits_this_month: number;
  pending_approvals: number;       // is_approve = false for today
}

export const DUMMY_TEAM: TeamMember[] = [
  {
    id: "emp-001",
    position: "Senior Software Engineer",
    department_id: "dept-01",
    department_name: "Engineering",
    company: "VisitMi Corp",
    created_at: "2022-03-15T00:00:00Z",
    user_id: "usr-001",
    first_name: "Priya",
    last_name: "Sharma",
    full_name: "Priya Sharma",
    email: "priya.sharma@visitmi.com",
    phone: "+91 98201 11001",
    last_login: "2025-05-15T08:42:00Z",
    total_visits_received: 68,
    visits_this_month: 14,
    pending_approvals: 2,
  },
  {
    id: "emp-002",
    position: "Finance Manager",
    department_id: "dept-02",
    department_name: "Finance",
    company: "VisitMi Corp",
    created_at: "2021-07-01T00:00:00Z",
    user_id: "usr-002",
    first_name: "Amit",
    last_name: "Joshi",
    full_name: "Amit Joshi",
    email: "amit.joshi@visitmi.com",
    phone: "+91 99887 22002",
    last_login: "2025-05-15T09:10:00Z",
    total_visits_received: 59,
    visits_this_month: 11,
    pending_approvals: 1,
  },
  {
    id: "emp-003",
    position: "Product Lead",
    department_id: "dept-03",
    department_name: "Product",
    company: "VisitMi Corp",
    created_at: "2023-01-10T00:00:00Z",
    user_id: "usr-003",
    first_name: "Divya",
    last_name: "Nair",
    full_name: "Divya Nair",
    email: "divya.nair@visitmi.com",
    phone: "+91 91234 33003",
    last_login: "2025-05-14T17:30:00Z",
    total_visits_received: 46,
    visits_this_month: 9,
    pending_approvals: 0,
  },
  {
    id: "emp-004",
    position: "Sales Director",
    department_id: "dept-04",
    department_name: "Sales",
    company: "VisitMi Corp",
    created_at: "2020-11-20T00:00:00Z",
    user_id: "usr-004",
    first_name: "Rahul",
    last_name: "Gupta",
    full_name: "Rahul Gupta",
    email: "rahul.gupta@visitmi.com",
    phone: "+91 88765 44004",
    last_login: "2025-05-15T10:05:00Z",
    total_visits_received: 35,
    visits_this_month: 7,
    pending_approvals: 3,
  },
  {
    id: "emp-005",
    position: "HR Business Partner",
    department_id: "dept-05",
    department_name: "HR",
    company: "VisitMi Corp",
    created_at: "2022-08-05T00:00:00Z",
    user_id: "usr-005",
    first_name: "Suresh",
    last_name: "Kumar",
    full_name: "Suresh Kumar",
    email: "suresh.kumar@visitmi.com",
    phone: "+91 97654 55005",
    last_login: "2025-05-13T14:20:00Z",
    total_visits_received: 27,
    visits_this_month: 5,
    pending_approvals: 0,
  },
  {
    id: "emp-006",
    position: "Legal Counsel",
    department_id: "dept-06",
    department_name: "Legal",
    company: "VisitMi Corp",
    created_at: "2021-04-12T00:00:00Z",
    user_id: "usr-006",
    first_name: "Ananya",
    last_name: "Mehta",
    full_name: "Ananya Mehta",
    email: "ananya.mehta@visitmi.com",
    phone: "+91 93456 66006",
    last_login: "2025-05-15T07:55:00Z",
    total_visits_received: 16,
    visits_this_month: 3,
    pending_approvals: 1,
  },
  {
    id: "emp-007",
    position: "DevOps Engineer",
    department_id: "dept-01",
    department_name: "Engineering",
    company: "VisitMi Corp",
    created_at: "2023-06-01T00:00:00Z",
    user_id: "usr-007",
    first_name: "Vikram",
    last_name: "Singh",
    full_name: "Vikram Singh",
    email: "vikram.singh@visitmi.com",
    phone: "+91 90123 77007",
    last_login: "2025-05-15T09:45:00Z",
    total_visits_received: 22,
    visits_this_month: 6,
    pending_approvals: 0,
  },
  {
    id: "emp-008",
    position: "Account Executive",
    department_id: "dept-04",
    department_name: "Sales",
    company: "VisitMi Corp",
    created_at: "2024-01-15T00:00:00Z",
    user_id: "usr-008",
    first_name: "Pooja",
    last_name: "Reddy",
    full_name: "Pooja Reddy",
    email: "pooja.reddy@visitmi.com",
    phone: "+91 86543 88008",
    last_login: null,
    total_visits_received: 9,
    visits_this_month: 2,
    pending_approvals: 0,
  },
  {
    id: "emp-009",
    position: "UX Designer",
    department_id: "dept-03",
    department_name: "Product",
    company: "VisitMi Corp",
    created_at: "2023-09-01T00:00:00Z",
    user_id: "usr-009",
    first_name: "Farhan",
    last_name: "Siddiqui",
    full_name: "Farhan Siddiqui",
    email: "farhan.siddiqui@visitmi.com",
    phone: "+91 93210 99009",
    last_login: "2025-05-14T11:00:00Z",
    total_visits_received: 19,
    visits_this_month: 4,
    pending_approvals: 2,
  },
  {
    id: "emp-010",
    position: "Tax Analyst",
    department_id: "dept-02",
    department_name: "Finance",
    company: "VisitMi Corp",
    created_at: "2022-12-01T00:00:00Z",
    user_id: "usr-010",
    first_name: "Meera",
    last_name: "Iyer",
    full_name: "Meera Iyer",
    email: "meera.iyer@visitmi.com",
    phone: "+91 86001 10010",
    last_login: "2025-05-15T08:00:00Z",
    total_visits_received: 31,
    visits_this_month: 8,
    pending_approvals: 0,
  },
];

export const DEPARTMENTS = [
  { id: "dept-01", name: "Engineering" },
  { id: "dept-02", name: "Finance" },
  { id: "dept-03", name: "Product" },
  { id: "dept-04", name: "Sales" },
  { id: "dept-05", name: "HR" },
  { id: "dept-06", name: "Legal" },
];